version: "3.8"

services:
  logistics_app: # 或者你之前设置的服务名，例如 web
    # build: .  # <--- 删除或注释掉 build 指令
    image: ghcr.io/cskeleton/logistics_finder:latest # <--- 指定要拉取的镜像
    ports:
      - "127.0.0.1:18000:8000"
    volumes:
      - /opt/logistics/:/app/data
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - UPLOAD_PASSWORD=${UPLOAD_PASSWORD}
    command: >
      sh -c "/app/scripts/download_data.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000"
